PORT_SCAN_CONFIG = {
    'default_timeout': 10,
    'max_retries': 2,
    'scan_speed': 'T4',
    'common_ports': [21, 22, 23, 25, 53, 80, 110, 143, 443, 993, 995, 1433, 3306, 3389, 5432, 5900, 8080],
    'critical_ports': [22, 23, 3389, 5900]
}

CMS_SCAN_CONFIG = {
    'timeout': 10,
    'user_agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
    'max_redirects': 5,
    'verify_ssl': False
}

REPORT_CONFIG = {
    'company_name': 'Automated Vulnerability Scanner',
    'report_title': 'Security Report',
    'logo_path': None,
    'footer_text': 'Automatically generated by the vulnerability scanner'
}

GUI_CONFIG = {
    'window_title': 'Automated Vulnerability Scanner - Local Businesses',
    'window_size': '900x700',
    'theme': 'default',
    'auto_save_logs': True,
    'log_file': 'scanner_log.txt'
}

SECURITY_CONFIG = {
    'max_concurrent_scans': 3,
    'rate_limit': 1.0,
    'whitelist_ips': [],
    'blacklist_ips': [],
    'require_authorization': False
}

COLORS = {
    'success': '#28a745',
    'warning': '#ffc107',
    'error': '#dc3545',
    'info': '#17a2b8',
    'primary': '#007bff',
    'secondary': '#6c757d'
}

MESSAGES = {
    'scan_started': 'Scan started...',
    'scan_completed': 'Scan completed successfully',
    'scan_failed': 'Scan failed',
    'no_target': 'Please provide a scan target',
    'no_cms_url': 'Please provide a CMS URL',
    'report_generated': 'Report has been generated',
    'report_failed': 'Failed to generate report',
    'unauthorized': 'You do not have permission to scan this target',
    'rate_limited': 'Scan limit exceeded, please try again later'
}

DEFAULT_SCAN_SETTINGS = {
    'scan_type': 'single',
    'scan_ports': True,
    'scan_cms': True,
    'quick_scan': False,
    'verbose_output': True
} 