# Port scanning configuration
PORT_SCAN_CONFIG = {
    'default_timeout': 10,
    'max_retries': 2,
    'scan_speed': 'T4',  # nmap timing template
    'common_ports': [21, 22, 23, 25, 53, 80, 110, 143, 443, 993, 995, 1433, 3306, 3389, 5432, 5900, 8080],
    'critical_ports': [22, 23, 3389, 5900],  # SSH, Telnet, RDP, VNC
    'aggressive_timeout': 2,
    'safe_timeout': 5,
    'banner_grab_timeout': 3,
    'connection_timeout': 10
}

# CMS scanning settings
CMS_SCAN_CONFIG = {
    'timeout': 10,
    'user_agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
    'max_redirects': 5,
    'verify_ssl': False,  # allow self-signed certs
    'request_timeout': 10,
    'head_timeout': 5,
    'version_check_timeout': 10
}

REPORT_CONFIG = {
    'company_name': 'ShieldEye Security',
    'report_title': 'Network Security Assessment',
    'logo_path': None,
    'footer_text': 'Generated by ShieldEye Scanner'
}

GUI_CONFIG = {
    'window_title': 'ShieldEye Scanner',
    'window_size': '900x700',
    'theme': 'default',
    'auto_save_logs': True,
    'log_file': 'shieldeye.log'
}

# Security and rate limiting
SECURITY_CONFIG = {
    'max_concurrent_scans': 3,
    'rate_limit': 1.0,  # requests per second
    'per_target_rate_limit': 2.0,
    'rate_limit_window': 60,  # seconds
    'max_requests_per_target': 100,
    'whitelist_ips': [],
    'blacklist_ips': [],
    'require_authorization': False
}

ASYNC_CONFIG = {
    'enabled': True,
    'max_concurrent_connections': 10,
    'connection_pool_size': 20,
    'semaphore_limit': 5,
    'timeout_total': 300
}

TIMEOUT_CONFIG = {
    'dns_lookup': 5,
    'ssl_handshake': 10,
    'web_vuln': 10,
    'http_request': 10,
    'socket_connect': 5,
    'banner_grab': 3,
    'port_scan': 5,
    'cms_scan': 15,
    'api_request': 30,
    'network_scan': 300,
    'cve_api': 20,
    'shodan_api': 10
}

ALERT_CONFIG = {
    'enabled': True,
    'score_threshold': 70,
    'min_level': 'HIGH',
}

COLORS = {
    'success': '#28a745',
    'warning': '#ffc107',
    'error': '#dc3545',
    'info': '#17a2b8',
    'primary': '#007bff',
    'secondary': '#6c757d'
}

MESSAGES = {
    'scan_started': 'Scan started...',
    'scan_completed': 'Scan completed successfully',
    'scan_failed': 'Scan failed',
    'no_target': 'Please provide a scan target',
    'no_cms_url': 'Please provide a CMS URL',
    'report_generated': 'Report has been generated',
    'report_failed': 'Failed to generate report',
    'unauthorized': 'You do not have permission to scan this target',
    'rate_limited': 'Scan limit exceeded, please try again later'
}

DEFAULT_SCAN_SETTINGS = {
    'scan_type': 'single',
    'scan_ports': True,
    'scan_cms': True,
    'quick_scan': False,
    'verbose_output': True
}

STEALTH_USER_AGENTS = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1",
    "Mozilla/5.0 (iPad; CPU OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0",
    "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)",
]

CRITICAL_PORTS_LIST = [22, 23, 80, 443, 3389, 5900]

COMMON_SUBDOMAINS = [
    'www', 'mail', 'ftp', 'localhost', 'webmail', 'smtp', 'pop', 'ns1', 'ns2',
    'webdisk', 'ns', 'cpanel', 'whm', 'autodiscover', 'autoconfig', 'api',
    'dev', 'staging', 'test', 'admin', 'blog', 'shop', 'forum', 'support'
]